version: '2'
services:
  server:
    image: dtandersen/factorio:0.16.51
    ports:
      - '34197:34197/udp'
      - '27015:27015/tcp'
    volumes:
      - ${PWD}/factorio:/factorio
    restart: always
