version: '2'
services:
  server:
    image: dtandersen/factorio:0.16.51
    ports:
      - '34197:34197/udp'
    volumes:
      - ${PWD}/factorio:/factorio
    restart: always
    stdin_open: true
    tty: true
